### ISSUE TITLE
Add environ support

### ISSUE THREAD

**Issue by dhvcc** [EgorEna/mail#1]
For security reasons, you should use local environment variables for sensitive data

---

I suggest using [python-dotenv](https://github.com/theskumar/python-dotenv)

Or [django-environ](https://github.com/joke2k/django-environ)

More about environment variables you can read [here](https://linuxize.com/post/how-to-set-and-list-environment-variables-in-linux/)

**Comment by EgorEna** [comment]
Thanks, I'll check those links

**Comment by dhvcc** [comment]
Guess I can call it resolves as for 530b47a4f793198c281a9b993f5e8fcddfc6dcfd

But, well, *changes* can be made
